package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'zerobugcurl'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("zerobugcurl")) {
    expectSteps {
        script {
            name = "curl"
            scriptContent = "curl -d 'token=5db63b48744bb86a21154f28cfd4c446&id_target=129&id=11001118' -X POST https://zerobug.co/build.php"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """curl -d "token=5db63b48744bb86a21154f28cfd4c446&id_target=129&id=11001118" -X POST https://zerobug.co/build.php"""
        }
    }
}
